### ISSUE TITLE
-0 is not normalized

### ISSUE THREAD

**Issue by acutmore** [seanmorris/libtuple.js#1]
In JavaScript `Map` and `Set` do not distinguish `0` and `-0` as different keys, instead `-0` is normalized to `0`.

This leads to the following 'bug':

```js
const Tuple = require('libtuple/Tuple');

if (Math.random() > 0.5) {
    Tuple(Object, -0); // sometimes create this first
} else {
    Tuple(Object, 0); // other times create this first
}

function isNegativeZero(n) {
  return Object.is(n, -0);
}

console.log(isNegativeZero(Tuple(Object, -0)[1])); // sometimes 'true', sometimes 'false'
```

**Comment by seanmorris** [comment]
Yea, that's a bug, they're definitely distinct values.

Change:
https://github.com/seanmorris/libtuple/blob/4b8373f90cf97a2fb06bba9e05f7bce9805116d6/Tuple.mjs#L115

Test:
https://github.com/seanmorris/libtuple/blob/4b8373f90cf97a2fb06bba9e05f7bce9805116d6/test/test.mjs#L739-L765

**Comment by seanmorris** [comment]
@acutmore would you mind taking a look at my other lib?

https://github.com/seanmorris/weaker
