### ISSUE TITLE
FinalizationRegistry race conditions

### ISSUE THREAD

**Issue by acutmore** [seanmorris/libtuple.js#2]
It looks like there are some race conditions with the way `FinalizationRegistry` is being used here.

It is possible for `WeakRef.prototype.deref` to return `undefined` before the `FinalizationRegistry` callback has been invoked. Technically it is spec complaint for `FinalizationRegistry` to never call the callbacks, the main thing that can't happen is for the callback to be invoked while the `WeakRef` still returns the value.

The two races are:

### 1) the callback happening after a Tuple is collected, but after the same Tuple has been created again.

https://github.com/seanmorris/libtuple.js/blob/ce255ce94ae30352dfb777ddeaae985cdff5c247/Tuple.js#L12

The callback here should double check that the map entry's `WeakRef` is still returning `undefined`, otherwise a new entry may have been created since the previous one was collected.

### 2) the `WeakRef` has been cleared but the `FinalizationRegistry` hasn't removed the entry yet

The code [here](https://github.com/seanmorris/libtuple.js/blob/ce255ce94ae30352dfb777ddeaae985cdff5c247/Tuple.js#L102) should check if the `WeakRef` returns `undefined`, rather than assume it will still contain the object.

Hope that is helpful!

**Comment by seanmorris** [comment]
I added some comments to make sure I don't accidentially "optimize" the fix out:

https://github.com/seanmorris/libtuple/blob/72478769b5652c32ef6cf157a969e48ee0991cfa/Tuple.mjs#L32-L40

https://github.com/seanmorris/libtuple/blob/72478769b5652c32ef6cf157a969e48ee0991cfa/Tuple.mjs#L133-L143

**Comment by acutmore** [comment]
Nice! I think this issue can be closed now?
